# Generated by Django 5.0 on 2024-01-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Book',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
